version: '3'
services:
  percona_model: # model
    image: percona:8.0
    env_file:
      - ./model/percona_model.env
    container_name: "percona_model"
    restart: "no"
    ports:
      - 4406:3306
    volumes:
      - ./model/conf/percona.conf.cnf:/etc/percona/conf.d/percona.conf.cnf
      - ./model/data:/var/lib/percona
    networks:
      - overlay

  percona_replica1:
    image: percona:8.0
    env_file:
      - ./replica/percona_replica.env
    container_name: "percona_replica1"
    restart: "no"
    ports:
      - 5506:3306
    depends_on:
      - percona_model
    volumes:
      - ./replica/conf/percona.conf.cnf:/etc/percona/conf.d/percona.conf.cnf
      - ./replica/data1:/var/lib/percona
    networks:
      - overlay

  percona_replica2:
    image: percona:8.0
    env_file:
      - ./replica/percona_replica.env
    container_name: "percona_replica2"
    restart: "no"
    ports:
      - 5507:3306
    depends_on:
      - percona_model
    volumes:
      - ./replica/conf/percona.conf.cnf:/etc/percona/conf.d/percona.conf.cnf
      - ./replica/data2:/var/lib/percona
    networks:
      - overlay

#  # dbproxy1:
#  #   image: percona/proxysql2
#     env_file:
#       - ./dbproxy/db-credential
#     container_name: dbproxy1
#     restart: "no"
#     ports:
#  #     - 16033:6033
#  #     - 16070:6070
#  #     - 16080:6080
#       depends_on:
#         - percona_model
#       volumes: 
#       - ./proxysql/proxysql.cnf:/etc/proxysql.cnf
#       - ./proxysql/data:/var/lib/proxysql
#     networks:
#       - overlay
      
networks:
  overlay:
